---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.2
before_install: gem install bundler -v 1.17.3
script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec srb tc
  - bundle exec rake
